import { ACTIONS_PREFIX } from '../constants';

export const PREFIX = `${ACTIONS_PREFIX}USER__`;

export const SINGLE_CREATE = `${PREFIX}SINGLE_CREATE`;
export const SINGLE_CREATE_SUCCESS = `${PREFIX}SINGLE_CREATE_SUCCESS`;
export const SINGLE_CREATE_FAILURE = `${PREFIX}SINGLE_CREATE_FAILURE`;

export const SINGLE_FETCH = `${PREFIX}SINGLE_FETCH`;
export const SINGLE_FETCH_SUCCESS = `${PREFIX}SINGLE_FETCH_SUCCESS`;
export const SINGLE_FETCH_FAILURE = `${PREFIX}SINGLE_FETCH_FAILURE`;
