import { ACTIONS_PREFIX } from '../constants';

export const PREFIX = `${ACTIONS_PREFIX}USER__`;

export const SINGLE_CREATE = `${PREFIX}SINGLE_CREATE`;
export const SINGLE_CREATE_SUCCESS = `${PREFIX}SINGLE_CREATE_SUCCESS`;
export const SINGLE_CREATE_FAILURE = `${PREFIX}SINGLE_CREATE_FAILURE`;

export const LOGIN = `${PREFIX}LOGIN`;
export const LOGIN_SUCCESS = `${PREFIX}LOGIN_SUCCESS`;
export const LOGIN_FAILURE = `${PREFIX}LOGIN_FAILURE`;

export const PERFORM_LOGOUT = `${PREFIX}PERFORM_LOGOUT`;
