import { ACTIONS_PREFIX } from '../constants';

export const PREFIX = `${ACTIONS_PREFIX}USER_LIST__`;

export const COLLECTION_FETCH = `${PREFIX}COLLECTION_FETCH`;
export const COLLECTION_FETCH_SUCCESS = `${PREFIX}COLLECTION_FETCH_SUCCESS`;
export const COLLECTION_FETCH_FAILURE = `${PREFIX}COLLECTION_FETCH_FAILURE`;
