import { ACTIONS_PREFIX } from '../constants';

export const PREFIX = `${ACTIONS_PREFIX}USER_LIST__`;

export const COLLECTION_FETCH = `${PREFIX}COLLECTION_FETCH`;
export const COLLECTION_FETCH_SUCCESS = `${PREFIX}COLLECTION_FETCH_SUCCESS`;
export const COLLECTION_FETCH_FAILURE = `${PREFIX}COLLECTION_FETCH_FAILURE`;

export const SINGLE_CREATE = `${PREFIX}SINGLE_CREATE`;
export const SINGLE_CREATE_SUCCESS = `${PREFIX}SINGLE_CREATE_SUCCESS`;
export const SINGLE_CREATE_FAILURE = `${PREFIX}SINGLE_CREATE_FAILURE`;

export const SINGLE_FETCH = `${PREFIX}SINGLE_FETCH`;
export const SINGLE_FETCH_SUCCESS = `${PREFIX}SINGLE_FETCH_SUCCESS`;
export const SINGLE_FETCH_FAILURE = `${PREFIX}SINGLE_FETCH_FAILURE`;

export const SINGLE_UPDATE = `${PREFIX}SINGLE_UPDATE`;
export const SINGLE_UPDATE_SUCCESS = `${PREFIX}SINGLE_UPDATE_SUCCESS`;
export const SINGLE_UPDATE_FAILURE = `${PREFIX}SINGLE_UPDATE_FAILURE`;

export const SINGLE_DELETE = `${PREFIX}SINGLE_DELETE`;
export const SINGLE_DELETE_SUCCESS = `${PREFIX}SINGLE_DELETE_SUCCESS`;
export const SINGLE_DELETE_FAILURE = `${PREFIX}SINGLE_DELETE_FAILURE`;
